title: "@silarin"
description: >-
  Python Developer | SQL Data Wrangler | Aspiring Algo Trader
  <br><br>
  <a href="#projects">📈 Projects</a><br>
  <a href="#skills">🚀 Technical Arsenal</a><br>
  <a href="#contact">📫 Contact</a>

show_downloads: false
google_analytics: 
theme: jekyll-theme-minimal
